### ISSUE TITLE
Not in the cards

### ISSUE THREAD

**Issue by trebird** [trebird/cards#1]
Hello,

I've followed the instructions, but I don't have any white boxes floating on a nice eggshell background. I'm not sure where it went wrong.

@thomasjbradley

**Comment by trebird** [comment]
Hi again,

I thought I'd fixed what was wrong, but I still don't know why the index isn't displaying properly.

Thanks in advance for your help!

@thomasjbradley

**Comment by thomasjbradley** [comment]
The CSS isn’t connected properly; this line here needs adjusting:
https://github.com/trebird/cards/blob/gh-pages/index.html#L7

You have the correct filename but you’re missing the `css` folder, like this:
`css/main.css`

**Comment by trebird** [comment]
Ouff-as if! Thank you!
